#!/usr/bin/env python3
"""
scripts/generate_sounds.py

Builds the Bark sound bank: one short file per bark / meow, so that one tap plays exactly
one vocalization. Several takes of the same animal are kept as variants; the app picks one
at random per tap so repeated taps sound natural.

Pipeline (requires numpy + scipy, no ffmpeg):
  1. Download the source clips from the ESC-50 dataset (only clips whose individual licence
     is CC0 or CC-BY, as listed in ESC-50's LICENSE file).
  2. Detect each vocalization by RMS energy (10 ms frames) and cut it out with a short
     pre-roll and its natural decay tail, never running into the next one.
  3. Drop faint, distant or clipped takes.
  4. High-pass filter (removes rumble/handling noise), match loudness across all sounds and
     cap peaks at -1 dBFS (no limiter, so no distortion), 3 ms fade-in / 40 ms fade-out.
  5. Write 16-bit mono WAV (no codec delay, so playback starts instantly) plus
     sounds/sounds.json, which the app reads.

Sounds listed in KEPT are existing files that are not regenerated here.
"""

import json
import urllib.request
from pathlib import Path

import numpy as np
from scipy.io import wavfile
from scipy.signal import butter, resample_poly, sosfiltfilt

BASE_DIR = Path(__file__).resolve().parent.parent
SOUNDS_DIR = BASE_DIR / "sounds"
CACHE_DIR = BASE_DIR / ".audio_cache"
ESC50 = "https://raw.githubusercontent.com/karolpiczak/ESC-50/master/audio/"

FRAME = 0.01          # analysis frame, seconds
TARGET_RMS_DB = -17   # loudness of the active part of each take
LOUD_RMS_DB = -11     # entries with loud=True (horns, whistle): still capped at PEAK_CEILING_DB
PEAK_CEILING_DB = -1
OUT_RATE = 32000       # keeps everything up to 16 kHz; ~30% smaller than 44.1 kHz

GENERATED = "Generated by scripts/generate_sounds.py (public domain)"

# Each entry: sources (ESC-50 files) or synth (generated), credit (from ESC-50's LICENSE),
# and optional selection limits (min_dur, max_dur, max_variants, merge_gap in seconds).
CATALOG = [
    # ---- Dogs ----
    dict(id="big_dog", category="dog", icon="🐕", title="Big Dog", desc="Deep single woof",
         sources=["4-182395-A-0.wav"],
         credit="Big_dog_bark_01.aiff by pgonsilva (freesound.org/s/182395), CC BY"),
    dict(id="guard_dog", category="dog", icon="🚨", title="Guard Dog", desc="Firm warning bark",
         sources=["4-191687-A-0.wav"],
         credit="Dog Barks.wav by UnderlinedDesigns (freesound.org/s/191687), CC0"),
    dict(id="spaniel", category="dog", icon="🦮", title="Springer Spaniel", desc="Bright, eager bark",
         sources=["1-110389-A-0.wav"],
         credit="animals_dog_bark_springer_spaniel_001.wav by soundscalpel.com (freesound.org/s/110389), CC BY"),
    dict(id="shih_tzu", category="dog", icon="🐶", title="Shih Tzu Pug", desc="Bark with a howly tail",
         sources=["3-180256-A-0.wav"], max_dur=1.0,
         credit="Dog Barking - Shih Tzu Pug by bspiller5 (freesound.org/s/180256), CC BY"),
    dict(id="dachshund", category="dog", icon="🌭", title="Mini Dachshund", desc="Lively indoor bark",
         sources=["4-192236-A-0.wav"],
         credit="Miniature Dachshund Bark - Indoors.wav by Ligidium (freesound.org/s/192236), CC0"),
    dict(id="poodle", category="dog", icon="🐩", title="Poodle", desc="Single sharp bark",
         sources=["3-170015-A-0.wav"],
         credit="one bark of a poodle dog by fabiopx (freesound.org/s/170015), CC0"),
    dict(id="yappy_pup", category="dog", icon="🐾", title="Yappy Pup", desc="High, snappy yip",
         sources=["5-9032-A-0.wav"],
         credit="Dog bark2.wav by MisterTood (freesound.org/s/9032), CC0"),
    # ---- Cats ----
    dict(id="classic_meow", category="cat", icon="🐱", title="Classic Meow", desc="Friendly meow",
         sources=["5-214759-A-5.wav", "5-214759-B-5.wav"], max_dur=1.3,
         credit="Cat meowing x5 by peridactyloptrix (freesound.org/s/214759), CC0"),
    dict(id="loud_meow", category="cat", icon="📢", title="Loud Meow", desc="Insistent, attention-seeking",
         sources=["5-172639-A-5.wav"], max_dur=1.0,
         credit="Cat.mp3 by telesik (freesound.org/s/172639), CC BY"),
    dict(id="hungry_cat", category="cat", icon="🥣", title="Hungry Cat", desc="Dinner-time demand",
         sources=["3-95695-A-5.wav", "3-95698-A-5.wav"], max_dur=1.2,
         credit="20100423.hungry.cats.02.wav / .05.wav by dobroide (freesound.org/s/95695, /95698), CC BY"),
    dict(id="soft_meow", category="cat", icon="🌙", title="Soft Meow", desc="Gentle, quiet mew",
         sources=["2-82274-A-5.wav", "2-82274-B-5.wav"], max_dur=1.2,
         credit="garage cat 01.wav by Kyster (freesound.org/s/82274), CC BY"),
    dict(id="little_mew", category="cat", icon="🍼", title="Little Mew", desc="Small, high mew",
         sources=["3-95697-A-5.wav"], max_dur=1.0,
         credit="20100423.hungry.cats.04.wav by dobroide (freesound.org/s/95697), CC BY"),
    dict(id="mad_cat", category="cat", icon="😾", title="Mad Cat Yowl", desc="Long, grumpy yowl",
         sources=["4-133047-C-5.wav"], max_dur=1.6,
         credit="MAD CAT !.wav by temawas (freesound.org/s/133047), CC0"),
    # ---- More: people, home & training sounds ----
    # Recorded (CC0). merge_gap bridges pauses so e.g. a knock-knock-knock is one sound.
    dict(id="cough", category="other", icon="😷", title="Cough", desc="\"Someone's here\" cough",
         sources=["5-209719-A-24.wav", "2-123896-A-24.wav", "3-142604-A-24.wav"], min_dur=0.15, max_dur=0.9,
         merge_gap=0.15,
         credit="Cough by Bramdv (freesound.org/s/209719), cough.wav by Sempoo (freesound.org/s/123896), "
                "cough1.mp3 by loisgwenllian (freesound.org/s/142604), CC0"),
    dict(id="door_knock", category="other", icon="🚪", title="Door Knock", desc="Knock-knock-knock",
         sources=["3-154378-A-30.wav", "5-235644-A-30.wav", "2-140841-A-30.wav"], min_dur=0.3, max_dur=2.0,
         merge_gap=0.45,
         credit="door knock.wav by semccab (freesound.org/s/154378), Door Knock.mp3 by Coonick "
                "(freesound.org/s/235644), Knocking on a Door by thecluegeek (freesound.org/s/140841), CC0"),
    dict(id="clap", category="other", icon="👏", title="Hand Clap", desc="One sharp clap",
         sources=["2-76408-A-22.wav", "2-76408-B-22.wav", "2-76408-C-22.wav", "2-76408-D-22.wav"], max_dur=0.5,
         credit="Clap.mp3 by therabidfrog (freesound.org/s/76408), CC0"),
    dict(id="can_open", category="other", icon="🥫", title="Can Opening", desc="Calls every cat in the house",
         sources=["2-144031-A-34.wav", "4-215635-A-34.wav", "3-147342-A-34.wav"], min_dur=0.15, max_dur=1.0,
         merge_gap=0.2,
         credit="Soda Can Open.aif by timgormly (freesound.org/s/144031), Open a can by edhutschek "
                "(freesound.org/s/215635), open_can2.wav by fuzzpapi (freesound.org/s/147342), CC0"),
    dict(id="car_horn", category="other", icon="🚗", title="Car Horn", desc="Short honk",
         sources=["4-178402-A-43.wav", "5-179860-A-43.wav", "5-179863-A-43.wav"], min_dur=0.15, max_dur=1.0, loud=True,
         credit="honk2.mp3 by genel (freesound.org/s/178402), car horn recordings by toiletrolltube "
                "(freesound.org/s/179860, /179863), CC0"),
    # Generated in code (see SYNTHS below).
    dict(id="clicker", category="other", icon="🖱️", title="Training Clicker", desc="Mark good behaviour",
         synth="clicker", loud=True, credit=GENERATED),
    dict(id="recall_whistle", category="other", icon="🎶", title="Recall Whistle", desc="Two rising whistles",
         synth="recall_whistle", loud=True, credit=GENERATED),
    dict(id="pet_corrector", category="other", icon="💨", title="Pet Corrector", desc="Sharp \"psst\" air hiss",
         synth="pet_corrector", credit=GENERATED),
    dict(id="air_horn", category="other", icon="📯", title="Air Horn", desc="Loud blast (startles dogs)",
         synth="air_horn", loud=True, credit=GENERATED),
    dict(id="doorbell", category="other", icon="🔔", title="Doorbell", desc="Ding-dong",
         synth="doorbell", credit=GENERATED),
]

# Existing files kept as-is (not produced by this script); see README for their sources.
KEPT = [
    dict(id="wolf_howl", category="dog", icon="🐺", title="Wolf Howl", desc="Long wild howl",
         files=["sounds/dog_wolf_howl.mp3"],
         credit="Wolf howls, U.S. Fish and Wildlife Service via Wikimedia Commons (public domain)"),
    dict(id="purr", category="cat", icon="💤", title="Purr", desc="Relaxed purring",
         files=["sounds/cat_gentle_purr.mp3"],
         credit="Purring cat by Mysid via Wikimedia Commons (public domain)"),
    dict(id="hiss", category="cat", icon="😼", title="Hiss", desc="Warning hiss",
         files=["sounds/cat_angry_hiss.mp3"],
         credit="Cat hissing by Zabuhailo via Wikimedia Commons (CC BY 3.0)"),
]

DEFAULTS = dict(dog=dict(min_dur=0.08, max_dur=0.7, max_variants=4, merge_gap=0.04),
                cat=dict(min_dur=0.25, max_dur=1.2, max_variants=4, merge_gap=0.04),
                other=dict(min_dur=0.05, max_dur=1.5, max_variants=3, merge_gap=0.04))
CATEGORY_ORDER = ["dog", "cat", "other"]


def load(name):
    CACHE_DIR.mkdir(exist_ok=True)
    path = CACHE_DIR / name
    if not path.exists():
        print(f"    downloading {name}")
        with urllib.request.urlopen(ESC50 + name) as resp:
            path.write_bytes(resp.read())
    sr, x = wavfile.read(path)
    x = x.astype(np.float32) / 32768
    if x.ndim > 1:
        x = x.mean(axis=1)
    return sr, x


def frame_db(x, hop):
    n = len(x) // hop
    rms = np.sqrt((x[: n * hop].reshape(n, hop) ** 2).mean(axis=1))
    return 20 * np.log10(rms + 1e-9)


def find_takes(sr, x, min_dur, max_dur, merge_gap):
    """Returns (start, end, peak_db) sample ranges of individual vocalizations."""
    hop = int(sr * FRAME)
    db = frame_db(x, hop)
    audible = db[db > -120]  # ignore digital silence padding
    floor = np.percentile(audible, 15)
    threshold = max(floor + 15, db.max() - 24)
    on = db > threshold

    # Group frames into events, bridging gaps shorter than merge_gap.
    bridge = int(round(merge_gap / FRAME)) + 1
    events, i, n = [], 0, len(db)
    while i < n:
        if not on[i]:
            i += 1
            continue
        j = i
        while j < n and on[j:j + bridge].any():
            j += 1
        events.append([i, j])
        i = j

    takes = []
    for k, (a, b) in enumerate(events):
        peak = db[a:b].max()
        # Extend to the natural decay: until 40 dB below the peak or near the noise floor,
        # but stop 20 ms before the next event.
        limit = events[k + 1][0] - 2 if k + 1 < len(events) else n
        end = b
        while end < limit and db[end] > max(peak - 40, floor + 6):
            end += 1
        start = max(0, a - 2)  # 20 ms pre-roll keeps the attack
        end = min(end, start + int(max_dur / FRAME))
        dur = (end - start) * FRAME
        seg = x[start * hop:end * hop]
        if dur < min_dur or np.abs(seg).max() > 0.98:  # too short, or clipped
            continue
        takes.append((start * hop, end * hop, peak))
    return takes


def finish(sr, seg, target_db=TARGET_RMS_DB):
    """Resample, high-pass, loudness match with a peak ceiling, and click-free fades."""
    if sr != OUT_RATE:
        g = np.gcd(sr, OUT_RATE)
        seg, sr = resample_poly(seg, OUT_RATE // g, sr // g), OUT_RATE
    sos = butter(2, 70, btype="highpass", fs=sr, output="sos")
    seg = sosfiltfilt(sos, seg)
    hop = int(sr * FRAME)
    db = frame_db(seg, hop)
    active = db > db.max() - 20
    rms_db = 10 * np.log10(np.mean(10 ** (db[active] / 10)))
    peak_db = 20 * np.log10(np.abs(seg).max() + 1e-9)
    gain_db = min(target_db - rms_db, PEAK_CEILING_DB - peak_db)
    seg = seg * 10 ** (gain_db / 20)
    fade_in, fade_out = int(sr * 0.003), int(sr * 0.04)
    seg[:fade_in] *= np.linspace(0, 1, fade_in)
    seg[-fade_out:] *= np.cos(np.linspace(0, np.pi / 2, fade_out)) ** 2
    return (np.clip(seg, -1, 1) * 32767).astype(np.int16)


# ---- Generated sounds (sample arrays at OUT_RATE) ----
def _t(dur):
    return np.arange(int(OUT_RATE * dur)) / OUT_RATE


def synth_clicker():
    """Box-clicker: a sharp metallic 'click' (press) and a softer one (release) 60 ms later."""
    rng = np.random.default_rng(1)
    out = np.zeros(int(OUT_RATE * 0.16))
    for offset, level in ((0.0, 1.0), (0.06, 0.55)):
        t = _t(0.03)
        body = np.sin(2 * np.pi * 3200 * t) + 0.6 * np.sin(2 * np.pi * 5100 * t) + 0.4 * rng.standard_normal(len(t))
        i = int(OUT_RATE * offset)
        out[i:i + len(t)] += level * body * np.exp(-t * 260)
    return out


def synth_recall_whistle():
    """Two short rising pea-whistle chirps with the whistle's characteristic trill."""
    parts = []
    for f0, f1, dur in ((2300, 3100, 0.22), (2500, 3400, 0.32)):
        t = _t(dur)
        freq = f0 + (f1 - f0) * np.clip(t / (dur * 0.6), 0, 1) + 90 * np.sin(2 * np.pi * 34 * t)
        tone = np.sin(2 * np.pi * np.cumsum(freq) / OUT_RATE)
        env = np.minimum(1, t / 0.015) * np.minimum(1, (dur - t) / 0.04)
        parts += [tone * env, np.zeros(int(OUT_RATE * 0.08))]
    return np.concatenate(parts)


def synth_pet_corrector(seed):
    """Compressed-air 'psst': a fast, bright burst of band-passed noise."""
    rng = np.random.default_rng(seed)
    dur = 0.55 + 0.1 * seed
    t = _t(dur)
    noise = rng.standard_normal(len(t))
    sos = butter(4, [2500, 9000], btype="bandpass", fs=OUT_RATE, output="sos")
    env = np.minimum(1, t / 0.01) * np.exp(-t * 2.2) * np.minimum(1, (dur - t) / 0.08)
    return sosfiltfilt(sos, noise) * env


def synth_air_horn():
    """Air horn: two slightly detuned, harmonic-rich reed tones a major third apart."""
    dur = 0.9
    t = _t(dur)
    tone = np.zeros(len(t))
    for f in (415, 523, 419):
        for h in range(1, 12):
            tone += np.sin(2 * np.pi * f * h * t) / h ** 1.1
    sos = butter(2, 3500, btype="lowpass", fs=OUT_RATE, output="sos")
    env = np.minimum(1, t / 0.03) * np.minimum(1, (dur - t) / 0.08)
    return np.tanh(1.5 * sosfiltfilt(sos, tone) / np.abs(tone).max()) * env


def synth_doorbell():
    """Ding-dong: two bell tones (E5, C5) with inharmonic partials and long decay."""
    def bell(f, dur):
        t = _t(dur)
        partials = ((1, 1.0, 3.0), (2.0, 0.5, 4.5), (2.76, 0.35, 6.0), (5.4, 0.15, 9.0))
        return sum(a * np.sin(2 * np.pi * f * r * t) * np.exp(-t * d) for r, a, d in partials)
    ding, dong = bell(659.3, 0.55), bell(523.3, 1.1)
    out = np.zeros(len(ding) + len(dong))
    out[:len(ding)] += ding
    out[int(OUT_RATE * 0.45):int(OUT_RATE * 0.45) + len(dong)] += dong
    return out


SYNTHS = {
    "clicker": lambda: [synth_clicker()],
    "recall_whistle": lambda: [synth_recall_whistle()],
    "pet_corrector": lambda: [synth_pet_corrector(0), synth_pet_corrector(1)],
    "air_horn": lambda: [synth_air_horn()],
    "doorbell": lambda: [synth_doorbell()],
}


def build(entry):
    target_db = LOUD_RMS_DB if entry.get("loud") else TARGET_RMS_DB
    if "synth" in entry:
        files = []
        for n, seg in enumerate(SYNTHS[entry["synth"]](), 1):
            rel = f"sounds/{entry['id']}_{n}.wav"
            wavfile.write(BASE_DIR / rel, OUT_RATE, finish(OUT_RATE, seg, target_db))
            files.append(rel)
            print(f"    {rel}: {len(seg) / OUT_RATE:.2f}s (generated)")
        return files
    opts = {**DEFAULTS[entry["category"]], **entry}
    takes = []  # (recording order, peak_db, sample rate, samples)
    for name in entry["sources"]:
        sr, x = load(name)
        for start, end, peak in find_takes(sr, x, opts["min_dur"], opts["max_dur"], opts["merge_gap"]):
            takes.append((len(takes), peak, sr, x[start:end]))
    if not takes:
        raise RuntimeError(f"no usable takes for {entry['id']}")
    # Keep the strongest takes (drops faint / distant ones), in recording order.
    loudest = max(t[1] for t in takes)
    takes = [t for t in takes if t[1] > loudest - 10]
    takes = sorted(sorted(takes, key=lambda t: -t[1])[: opts["max_variants"]])
    files = []
    for n, (_, _, sr, seg) in enumerate(takes, 1):
        rel = f"sounds/{entry['id']}_{n}.wav"
        wavfile.write(BASE_DIR / rel, OUT_RATE, finish(sr, seg, target_db))
        files.append(rel)
        print(f"    {rel}: {len(seg) / sr:.2f}s")
    return files


def main():
    SOUNDS_DIR.mkdir(exist_ok=True)
    for old in SOUNDS_DIR.glob("*.wav"):
        old.unlink()
    bank = []
    for entry in CATALOG:
        print(f"[*] {entry['title']}")
        files = build(entry)
        bank.append({k: entry[k] for k in ("id", "category", "icon", "title", "desc", "credit")} | {"files": files})
    bank += [dict(entry) for entry in KEPT]
    bank.sort(key=lambda s: CATEGORY_ORDER.index(s["category"]))  # stable within a category
    (SOUNDS_DIR / "sounds.json").write_text(json.dumps(bank, ensure_ascii=False, indent=1) + "\n")
    size = sum(f.stat().st_size for f in SOUNDS_DIR.glob("*.wav"))
    print(f"Wrote {sum(len(s['files']) for s in bank)} files; generated WAVs total {size / 1024:.0f} KB")


if __name__ == "__main__":
    main()
